version: '3.9'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
  testpy:
    image: python:3.12
    volumes:
      - ./test.py:/test.py
      - ./requirements.txt:/requirements.txt
    env_file:
      - .env
    command: ["sh", "-c", "pip install -r /requirements.txt && python /test.py"]
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3