app = "notification-service"
primary_region = "ams" # если другой регион — замени

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1
  ports = [
    { port = 80, handlers = ["http"] },
    { port = 443, handlers = ["tls", "http"] }
  ]

[[services]]
  internal_port = 5672
  protocol = "tcp"
  processes = ["app"]
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1
  ports = [
    { port = 5672 } # открываем RabbitMQ наружу (для других сервисов)
  ]
[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1 