app = "fitness-app-notification"
primary_region = "fra"

[build]

# HTTP сервис Notification API
[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
