app = "fitness-app-notification"
primary_region = "fra"

[build]

# HTTP сервис Notification API
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "10s"
    restart_limit = 0
    port = 8080

# RabbitMQ - внешний доступ по 5672
[[services]]
  internal_port = 5672
  protocol = "tcp"
  processes = ['app']
  
  [[services.ports]]
    port = 5672
    handlers = []

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000
    grace_period = "10s"
    restart_limit = 0
    port = 5672


[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
