// <auto-generated />
using Fitness_App_Notification.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fitness_App_Notification.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20250529105523_InitNotificationPrefs")]
    partial class InitNotificationPrefs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fitness_App_Notification.Models.NotificationPreferences", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("ChallengeInvite")
                        .HasColumnType("boolean");

                    b.Property<bool>("ChallengeResponse")
                        .HasColumnType("boolean");

                    b.Property<bool>("FriendInvite")
                        .HasColumnType("boolean");

                    b.Property<bool>("FriendResponse")
                        .HasColumnType("boolean");

                    b.HasKey("Email");

                    b.ToTable("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
