name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # или другая ветка, с которой деплоишь

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'  # версию укажи в зависимости от SDK

    - name: Build project
      run: dotnet publish -c Release -o ./out

    - name: Install Fly CLI
      uses: superfly/flyctl-actions/setup-flyctl@master

    - name: Deploy to Fly.io
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      run: flyctl deploy --remote-only
